/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculatorcat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enock
 */
public class HomePage extends javax.swing.JFrame {

    /** Creates new form HomePage */
    public HomePage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fnumber = new javax.swing.JTextField();
        snumber = new javax.swing.JTextField();
        addradiobtn = new javax.swing.JRadioButton();
        subradiobtn = new javax.swing.JRadioButton();
        multradiobtn = new javax.swing.JRadioButton();
        divradiobtn = new javax.swing.JRadioButton();
        savebtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultTbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CAT II Calc System");

        jLabel2.setText("F.Number");

        jLabel3.setText("S.Number");

        addradiobtn.setText("+");
        addradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addradiobtnActionPerformed(evt);
            }
        });

        subradiobtn.setText("-");
        subradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subradiobtnActionPerformed(evt);
            }
        });

        multradiobtn.setText("*");
        multradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multradiobtnActionPerformed(evt);
            }
        });

        divradiobtn.setText("/");
        divradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divradiobtnActionPerformed(evt);
            }
        });

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        ResultTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "1st Number", "Operator", "2nd Number", "Answer", "Date"
            }
        ));
        ResultTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jScrollPane1.setViewportView(ResultTbl);
        if (ResultTbl.getColumnModel().getColumnCount() > 0) {
            ResultTbl.getColumnModel().getColumn(0).setResizable(false);
            ResultTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel4.setText("Result Table");

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(snumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addradiobtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subradiobtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(multradiobtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(divradiobtn)
                                .addGap(18, 18, 18)
                                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addradiobtn)
                    .addComponent(subradiobtn)
                    .addComponent(multradiobtn)
                    .addComponent(divradiobtn)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(snumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(savebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutbtn)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addradiobtnActionPerformed
        if(addradiobtn.isSelected()){
            subradiobtn.setSelected(false);
           divradiobtn.setSelected(false);
           multradiobtn.setSelected(false);
        }
    }//GEN-LAST:event_addradiobtnActionPerformed

    private void subradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subradiobtnActionPerformed
        if(subradiobtn.isSelected()){
            addradiobtn.setSelected(false);
           divradiobtn.setSelected(false);
           multradiobtn.setSelected(false);
        }
    }//GEN-LAST:event_subradiobtnActionPerformed

    private void multradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multradiobtnActionPerformed
        if(multradiobtn.isSelected()){
           addradiobtn.setSelected(false);
           divradiobtn.setSelected(false);
           subradiobtn.setSelected(false);
        }
    }//GEN-LAST:event_multradiobtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        SaveOperationMethod();
    }//GEN-LAST:event_savebtnActionPerformed

    private void divradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divradiobtnActionPerformed
        if(divradiobtn.isSelected()){
           addradiobtn.setSelected(false);
           multradiobtn.setSelected(false);
           subradiobtn.setSelected(false);
        }
    }//GEN-LAST:event_divradiobtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        searchingMethod();
    }//GEN-LAST:event_searchbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        LoginForm l = new LoginForm();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ResultTbl;
    private javax.swing.JRadioButton addradiobtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JRadioButton divradiobtn;
    private javax.swing.JTextField fnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JRadioButton multradiobtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField snumber;
    private javax.swing.JRadioButton subradiobtn;
    // End of variables declaration//GEN-END:variables

    private void CheckWithRadioBtn() {
        if(fnumber.getText().equals("") || snumber.getText().equals("")){
            JOptionPane.showMessageDialog(null, "All Fields is Required!");
        }
        else if(addradiobtn.isSelected()){
           String num1 =fnumber.getText();
           String num2 = snumber.getText();
           String op ="+";
           int Result = Integer.valueOf(num1)+ Integer.valueOf(num2);
            OperationMethod(num1,num2,op,Result);
        }else if(subradiobtn.isSelected()){
           String num1 =fnumber.getText();
           String num2 = snumber.getText();
           String op ="-";
           int Result = Integer.valueOf(num1)-Integer.valueOf(num2);
            OperationMethod(num1,num2,op,Result);
        }else if(multradiobtn.isSelected()){
           String num1 =fnumber.getText();
           String num2 = snumber.getText();
           String op ="*";
           int Result = Integer.valueOf(num1)*Integer.valueOf(num2);
            OperationMethod(num1,num2,op,Result);
        }else if(divradiobtn.isSelected()){
           String num1 =fnumber.getText();
           String num2 = snumber.getText();
           String op ="/";
           int Result = Integer.valueOf(num1)/Integer.valueOf(num2);
            OperationMethod(num1,num2,op,Result);
        }else{
            JOptionPane.showMessageDialog(null, "Please Check one Operation !");
        }
    }

    private void OperationMethod(String num1, String num2,String op, int Result) {
        
        String numone = num1;
        String numtwo = num2;
        String op1 = op;
        int Res = Result;
        String USERNAME="enock";
        String PASSWORD="enock";  
        String CON_STRING="jdbc:mysql://localhost:3306/iprc_tumba_2021";
        Connection con = null;
//        System.out.println("the re is :" + Result);
        
           try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(CON_STRING,USERNAME,PASSWORD);
            Statement statement= con.createStatement();
            if(con != null){
                if(fnumber.getText().equals("") && snumber.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "All Fields is Required!");
                }else{
//                    JOptionPane.showMessageDialog(null, "connection ok");
                   
                  String query1 = "INSERT INTO `operation`(`Operand1`, `Operand2`, `Operator`, `Result`) VALUES ('"+numone+"','"+numtwo+"','"+op1+"','"+Res+"')";
                  statement.executeUpdate(query1);
                  JOptionPane.showMessageDialog(null, "Operation Done!");
                 
                }       
            }else{
                JOptionPane.showMessageDialog(null, "connection Failed");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    private void SaveOperationMethod() {
        CheckWithRadioBtn();
    
    }

    private void searchingMethod() {
       
        String searchText= searchtxt.getText();
         String USERNAME="enock";
        String PASSWORD="enock";  
        String CON_STRING="jdbc:mysql://localhost:3306/iprc_tumba_2021";
        Connection con = null;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(CON_STRING,USERNAME,PASSWORD);
             Statement statement= con.createStatement();
        //selecting data from the Database
                  String selectQuery="SELECT * FROM operation WHERE ActionDate LIKE '%"+searchText+"%'";
                  ResultSet rs= statement.executeQuery(selectQuery);
                  DefaultTableModel tm =(DefaultTableModel) ResultTbl.getModel();
                  tm.setRowCount(0);
                  while(rs.next()){
                      Object o[]={rs.getInt("OperationId"),rs.getString("Operand1"),rs.getString("Operator"),rs.getString("Operand2"),rs.getString("Result"),rs.getString("ActionDate")};
                        tm.addRow(o);
                  }
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }

}
